//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string idtipodocumento { get; set; }
        public Nullable<int> documento { get; set; }
        public string lugarresidencia { get; set; }
        public string fechanacimiento { get; set; }
        public string email { get; set; }
        public Nullable<int> telefono { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
    }
}
